# Config file for automatic testing at travis-ci.org

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "pypy"
  - "3.5"
  - "3.6"

install:
  - "pip install --upgrade pip"
  - "python setup.py install"
  - "pip install -e .[dev]"

script:
  - "coverage run --source=expurgator -m py.test --verbose tests"

after_success:
  coveralls
